# Generated by Django 4.0.3 on 2022-06-13 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_machine_mach_machine_maintenancedate'),
    ]

    operations = [
        migrations.CreateModel(
            name='infrastructure',
            fields=[
                ('lieu', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('machines', models.IntegerField()),
                ('manager', models.CharField(max_length=20)),
                ('employe', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='mach',
            field=models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'MAc - Run MacOS '), ('Serveur', ' Serveur - Simple Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 20, 22, 23, 630522)),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('secu', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('prenom', models.CharField(max_length=15)),
                ('lieu', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.infrastructure')),
            ],
        ),
    ]
