# Generated by Django 4.0.3 on 2022-06-13 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0003_infrastructure_alter_machine_mach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 20, 34, 41, 866017)),
        ),
    ]
